spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ceos19
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
logging:
  level:
    org.hibernate.sql: debug
